/* eslint-disable */
/**
 * Generated by convex codegen.
 * This is a temporary stub — it will be overwritten by `npx convex dev`.
 */
import { anyApi } from "convex/server";

// Stub: uses Convex's proxy-based anyApi so that api.module.function resolves
// to valid FunctionReference objects at runtime (required by useQuery/useMutation/useAction).
// The real generated version is schema-aware. This stub uses `any` to unblock typecheck.
export const internal: any = anyApi;
export const api: any = anyApi;
